AWSTemplateFormatVersion: "2010-09-09"
Description: Emotions Project - CloudFormation Template

Resources:
  NotebookRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "sagemaker.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "SageMakerRole"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: "*"

  NotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      InstanceType: "ml.t2.large"
      NotebookInstanceName: "rekognition-video-analysis-notebook"
      RoleArn: !GetAtt NotebookRole.Arn

Outputs:
  Instance:
    Description: SageMaker Notebook Instance.
    Value: !Ref NotebookInstance
  Role:
    Description: SageMaker Notebook Instance Role.
    Value: !GetAtt NotebookRole.Arn
